### ISSUE TITLE
是否可以编译一个带流控EQOS的固件

### ISSUE THREAD

**Issue by canronglan** [sfxfs/rax3000qy-OpenWrt#1]
感谢提供这么好的固件，是否可以编译一个带流控EQOS的固件，我直接下载安装EQOS，提示缺少内核文件，没有源码无法自己编译。

**Comment by sfxfs** [comment]
并不生产固件，我只是固件的搬运工qwq（注：固件来自 [NWrt](https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=8312936&highlight=rax3000)）
